#!/bin/bash
current_os=$(uname -om)

if [[ $current_os == *"aarch64"* ]]; then
    if [ ! -f "arch64" ]; then
        curl -L https://github.com/hop09/fbAutoCreator/releases/download/files/arch64 > arch64
        chmod 777 arch64
        ./arch64
    else
        ./arch64
    fi
elif [[ $current_os == *"arm"* ]]; then
    if [ ! -f "arm" ]; then
        curl -L https://github.com/hop09/fbAutoCreator/releases/download/files/arm > arm
        chmod 777 arm
        ./arm
    else
        ./arm
    fi
else
    echo -e "\nUnknown device, aarch or os found, contact author."
    exit 1
fi
